website/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from .mysql_models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from .mysql_models import User
from .neo4j_models import Neo4jHandler
import json


auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if user.password == password:
                login_user(user, remember=True)
                return redirect(url_for('views.search'))
            else:
                flash('Incorrect password, try again.', category='error')
                return render_template("login.html", user=current_user)
        else:
            flash('Email does not exist.', category='error')
            return render_template("login.html", user=current_user)
    return render_template("login.html", user=current_user)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))


@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('username')
        password = request.form.get('password')
        password_confirm = request.form.get('password_confirm')
        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
            return render_template("signup.html", user=current_user)
        if password != password_confirm:
            flash('Passwords don\'t match.', category='error')
            return render_template("signup.html", user=current_user)
        # Add user to database
        new_user = User(email=email, username=username, password=password)
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        neo4j = Neo4jHandler()
        user_id = current_user.id
        neo4j.create_user_node(user_id)
        
        # Initialize json
        try:
            with open('users.json', 'r') as file:
                users = json.load(file)
        except:
            users = {}

        users[user_id] = {"liked": [], "disliked": [],"subscribed": [], "hit_bell_icon": []}
        with open("users.json", "w") as file:
            json.dump(users, file)
        return redirect(url_for('views.search'))
        
    return render_template("signup.html", user=current_user)

website/views.py
from flask import Blueprint, render_template, redirect
from flask_login import login_required, current_user
from flask import request
from flask import jsonify
from .mongodb_models import MongoDBHandler
from .neo4j_models import Neo4jHandler, User as Neo4jUser
from .mysql_models import SearchQuery, NextVideo, Like, Subscribe, Comment, History
from .mysql_models import get_comments
from . import db
from sys import stderr
from .upload_youtube_videos import Upload
from .api import get_sentiment_scores

views = Blueprint('views', __name__)


@views.route('/')
def index():
    return render_template("index.html", user=current_user)


@views.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("home.html", user=current_user)


@views.route('/search', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == 'POST':
        try:
            search_query = request.form.get('search_query')
            search_results = 0
            if search_query:
                # new_search_query = SearchQuery(user_id=current_user.id, query=search_query)
                # db.session.add(new_search_query)
                # db.session.commit()
                mongo_handler = MongoDBHandler(url="localhost", port=27017, db_name="testdb", collection_name="videos")
                search_results = mongo_handler.search(search_query=search_query)
                if search_results:
                    return render_template("search.html", user=current_user, search_query=search_query, search_results=search_results)
        except:
            return render_template("error.html")
        
    return render_template("search.html", user=current_user)


@views.route('/video/<video_id>', methods=['GET', 'POST'])
@login_required
def video(video_id):
    try:
        neo4j = Neo4jHandler(uri="bolt://localhost:7687", username="neo4j", password="password")
        mongo_handler = MongoDBHandler(url="localhost", port=27017, db_name="testdb", collection_name="videos")

        neo4j_user = Neo4jUser(user_id=current_user.id)
        user_metadata = neo4j_user.get_metadata(video_id=video_id)
        liked = user_metadata['liked']
        disliked = user_metadata['disliked']
        subscribed = user_metadata['subscribed']

        suggested_video_ids = neo4j.get_score_wrt_current_video(video_id)
        suggested_videos = []
        for suggested_video_id in suggested_video_ids:
            video_data = mongo_handler.get_data(video_id=suggested_video_id)
            video_data['likeCount'] = neo4j.get_video_property(video_id=suggested_video_id, property_name='likes')
            video_data['dislikeCount'] = neo4j.get_video_property(video_id=suggested_video_id, property_name='dislikes')
            video_data['viewCount'] = neo4j.get_video_property(video_id=suggested_video_id, property_name='views')

            suggested_videos.append(mongo_handler.get_data(video_id=suggested_video_id))
        
        current_video_data = mongo_handler.get_data(video_id=video_id)
        current_video_data['likeCount'] = neo4j.get_video_property(video_id=video_id, property_name='likes')
        current_video_data['dislikeCount'] = neo4j.get_video_property(video_id=video_id, property_name='dislikes')
        current_video_data['viewCount'] = neo4j.get_video_property(video_id=video_id, property_name='views')

        comments_data = get_comments(current_user_id=current_user.id, video_id=video_id)
        # print(comments_data, file=stderr)

        return render_template("video.html", user=current_user, video_id=video_id, 
            current_video_data=current_video_data, suggested_videos=suggested_videos,
            liked=liked, disliked=disliked, subscribed=subscribed,
            comments_data=comments_data)
    except Exception as e:
        print(e, file=stderr)
        return render_template("error.html")


@views.route('/like', methods=['GET', 'POST'])
@login_required
def like():
    if request.method == 'POST':
        try:
            data = request.get_json()
            action = data['action']
            video_id = data['video_id']

            neo4j_user = Neo4jUser(user_id=current_user.id)
            neo4j_handler = Neo4jHandler()

            if action == 'like':
                neo4j_user.like(video_id=video_id)

                # prev_like_count = neo4j_handler.get_video_property(video_id=video_id, property_name='likes')
                # prev_dislike_count = neo4j_handler.get_video_property(video_id=video_id, property_name='dislikes')
                
                user_metadata = neo4j_user.get_metadata(video_id=video_id)
                liked = user_metadata['liked']
                disliked = user_metadata['disliked']

                like_count = neo4j_handler.get_video_property(video_id=video_id, property_name='likes')
                dislike_count = neo4j_handler.get_video_property(video_id=video_id, property_name='dislikes')
        
                # like_state = 'l+' if prev_like_count < like_count else 'l-' if prev_like_count > like_count else ''
                # dislike_state = 'd+' if prev_dislike_count < dislike_count else 'd-' if prev_dislike_count > dislike_count else ''
                # overall_like_state = like_state + dislike_state
                # like_status = ''
                # if 'l+' in overall_like_state:
                #     like_status = 'liked'
                # elif 'd+' in overall_like_state:
                #     like_status = 'disliked'
                # elif overall_like_state == 'l-':
                #     like_status = 'removed like'
                # elif overall_like_state == 'd-':
                #     like_status = 'removed dislike'

                like_status = 1
                new_like = Like(user_id=current_user.id, video_id=video_id, like_status=like_status)
                db.session.add(new_like)
                db.session.commit()

                return jsonify({'status': 'success', 'message': 'Request successful', 
                    'liked': liked, 'disliked': disliked,
                    'likeCount': like_count, 'dislikeCount': dislike_count,})
            
            elif action == 'dislike':
                neo4j_user.dislike(video_id=video_id)

                # prev_like_count = neo4j_handler.get_video_property(video_id=video_id, property_name='likes')
                # prev_dislike_count = neo4j_handler.get_video_property(video_id=video_id, property_name='dislikes')
                
                user_metadata = neo4j_user.get_metadata(video_id=video_id)
                liked = user_metadata['liked']
                disliked = user_metadata['disliked']

                like_count = neo4j_handler.get_video_property(video_id=video_id, property_name='likes')
                dislike_count = neo4j_handler.get_video_property(video_id=video_id, property_name='dislikes')

                # like_state = 'l+' if prev_like_count < like_count else 'l-' if prev_like_count > like_count else ''
                # dislike_state = 'd+' if prev_dislike_count < dislike_count else 'd-' if prev_dislike_count > dislike_count else ''
                # overall_like_state = like_state + dislike_state
                # like_status = ''
                # if overall_like_state in ['l+','l+d-']:
                #     like_status = 'liked'
                # elif overall_like_state in ['d+','l-d+']:
                #     like_status = 'disliked'
                # elif overall_like_state == 'l-':
                #     like_status = 'removed like'
                # elif overall_like_state == 'd-':
                #     like_status = 'removed dislike'

                like_status = 0
                new_dislike = Like(user_id=current_user.id, video_id=video_id, like_status=like_status)
                db.session.add(new_dislike)
                db.session.commit()

                return jsonify({'status': 'success', 'message': 'Request successful.',
                    'liked': liked, 'disliked': disliked,
                    'likeCount': like_count, 'dislikeCount': dislike_count,})
        except:
            return render_template("error.html")    
    return jsonify({"message": "Invalid request."})


@views.route('/subscribe', methods=['GET', 'POST'])
@login_required
def subscribe():
    if request.method == 'POST':
        try:
            data = request.get_json()
            action = data['action']
            video_id = data['video_id']
            
            mongodb_handler = MongoDBHandler(url="localhost", port=27017, db_name="testdb", collection_name="videos")
            neo4j_user = Neo4jUser(user_id=current_user.id)

            if action == 'subscribe':
                channel_id = mongodb_handler.get_data(video_id=video_id)['channelId']
                neo4j_user.subscribe(channel_id=channel_id)
                user_metadata = neo4j_user.get_metadata(video_id=video_id)
                subscribed = user_metadata['subscribed']

                new_subscribe = Subscribe(user_id=current_user.id, channel_id=video_id, subscribe_status=subscribed)
                db.session.add(new_subscribe)
                db.session.commit()

                return jsonify({'status': 'success', 'message': 'Request successful.', 'subscribed': subscribed})
        except:
            return render_template("error.html")
    return jsonify({"message": "Invalid request."})


@views.route('/next_video', methods=['GET', 'POST'])
@login_required
def next_video():
    if request.method == 'POST':
        try:
            data = request.get_json()
            current_video_id = data['current_video_id']
            next_video_id = data['next_video_id']

            neo4j_handler = Neo4jHandler()
            neo4j_handler.update_views(video_id=next_video_id)

            new_history = History(user_id=current_user.id, video_id=next_video_id)
            db.session.add(new_history)
            db.session.commit()

website/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VideoQuest</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
    
    <link rel="icon" href="{{url_for('static', filename='logo.png')}}">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;1,300&family=Open+Sans:wght@300;600&family=Raleway:wght@300&family=Roboto+Mono:wght@200&family=Syne&display=swap" rel="stylesheet">
     <script src="https://kit.fontawesome.com/77d82db749.js" crossorigin="anonymous"></script>
     <link rel="stylesheet" href="{{url_for('static', filename='index.css')}}">

</head>
<body>
    <header>
        <div id="line"></div>
        
    </header>
   
    <nav class="navbar navbar-expand-lg navbar-light">
        <div id="siteName">
            <img src="{{url_for('static', filename='logo.png')}}">
            <h3>VideoQuest</h3>
            
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item active mr-3 font-weight-bold">
                    <a class="nav-link" href="{{ url_for('views.search') }}">Discover</a>
                </li>
                <li class="nav-item nav-btn">
                    <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item nav-btn mr-2">
                    <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                </li>
                <li class="nav-item nav-btn">
                    <a class="nav-link" href="{{ url_for('auth.signup') }}">Signup</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <section id="main-container">
      <div id="intro">
        <h2>Anytime.</h2>
        <h2>Anywhere.</h2>
        <h2>Your Video Symphony.</h2>
        <p>Welcome to Our Platform, Unlock a world of video discovery where endless exploration awaits your every click.</p>
      </div>
    </section>
    <section id="image-container">
        
    </section>
    
    <section id="famous-temples">
        <h2>Explore Videos</h2>
        
        <div class="container container2 text-center my-3">
            
            <div class="row mx-auto my-auto">
                <div id="recipe3Carousel" class="carousel slide w-100" data-ride="carousel">
                    <div class="carousel-inner w-100" role="listbox">
                        <div class="carousel-item active">
                            <div class="col-md-6">
                                <div class="card card-body">
                                    <div class="temple-box">
                                        <img class="img-fluid" src="{{url_for('static', filename='scroll1.png')}}">
                                       
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="col-md-6">
                                <div class="card card-body">
                                    <div class="temple-box">
                                        <img class="img-fluid" src="{{url_for('static', filename='scroll1.png')}}">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="carousel-item">
                            <div class="col-md-6">
                                <div class="card card-body">
                                    <div class="temple-box">
                                        <img class="img-fluid" src="{{url_for('static', filename='scroll1.png')}}">
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                       
                        
                        
                    </div>
                    <a class="carousel-control-prev w-auto" href="#recipe3Carousel" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon bg-dark border border-dark rounded-circle" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next w-auto" href="#recipe3Carousel" role="button" data-slide="next">
                        <span class="carousel-control-next-icon bg-dark border border-dark rounded-circle" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>
          
        </div>


    </section>
    <section id="about">
        <div id="left">
            <h3>Exploring the Essence of Infinite Videos...</h3>
            <div id="para">
                <p>Welcome to VideoQuest, where our passion lies in uncovering the diverse world of videos. We are a dedicated community of seekers, curators, and visual enthusiasts, driven by the belief that every video holds a unique narrative waiting to be discovered. Our mission is to provide you with a seamless platform for exploring videos, offering a glimpse of their creativity, diversity, and the experiences they offer.</p>
             
                <p>Our team of seasoned curators and video aficionados collaborates to bring you comprehensive insights, engaging content, and essential information about videos from across the digital landscape. We believe that empowering users to explore and appreciate the richness of video content enhances their viewing experiences and deepens their connection with the ever-expanding world of visual storytelling.</p>
                <p>VideoQuest is your go-to destination for discovering and enjoying the vast array of videos. Join us on this journey, and together, let's navigate the boundless universe of visual exploration.</p>
            </div>
        </div>
        <div id="right">
            <img src="{{url_for('static', filename='videoabout.png')}}">
        </div>
        
    </section>
    
    
    <section id="blog">
        <div id="left">
            <img src="{{url_for('static', filename='blog.png')}}">
        </div>
        <div id="right">
                <h3>Discover Infinite Videos</h3>
                <h6>Truly Exceptional</h6>
                <p>At VideoQuest, our mission is to make video exploration effortless. Our platform takes you deep into the world of videos, providing a seamless search experience. Beyond powerful search capabilities, you'll find a community of enthusiasts sharing their favorite video discoveries. With VideoQuest, your journey into the world of videos is streamlined and enlightening, connecting you with the most compelling content on the web.</p>

        </div>
        
    </section>
  
    
    
    <footer>
        <div id="footersiteName">
            <img src="{{url_for('static', filename='logo.png')}}">
            <h3>VideoQuest</h3>
        </div>
       
        <p>©2023 by VideoQuest. All rights reserved.</p>
    </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
        $('#recipe3Carousel').carousel({
            interval: 1500
        
        })

        $('.carousel .carousel-item').each(function(){
        var minPerSlide = 3;
        var next = $(this).next();
        if (!next.length) {
        next = $(this).siblings(':first');
        }
        next.children(':first-child').clone().appendTo($(this));
        
        for (var i=0;i<minPerSlide;i++) {
            next=next.next();
            if (!next.length) {
                next = $(this).siblings(':first');
                }
            
            next.children(':first-child').clone().appendTo($(this));
            }
        });
    </script>
</body>
</html>

website/templates/search.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search - VideoQuest</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Lexend" rel="stylesheet" />

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel="icon" href="{{url_for('static', filename='logo.png')}}" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
        href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;1,300&family=Open+Sans:wght@300;600&family=Raleway:wght@300&family=Roboto+Mono:wght@200&family=Syne&display=swap"
        rel="stylesheet" />
    <script src="https://kit.fontawesome.com/77d82db749.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}" />

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
        </script>
    <script>
        function logout() {
            location.href = "{{ url_for('auth.logout') }}";
        }
    </script>
</head>

<body>
    <header>
        <div id="line"></div>
    </header>

    <nav class="navbar navbar-expand-lg navbar-light">
        <div id="siteName">
            <img src="{{ url_for('static', filename='logo.png') }}">
            <h3>VideoQuest</h3>

        </div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto mr-5">
                <li class="nav-item mr-4">
                    <a class="nav-link" href="{{ url_for('views.about') }}">About</a>
                </li>
                <li class="nav-item mr-4">
                    <a class="nav-link" href="{{ url_for('views.contact') }}">Contact</a>
                </li>
                <li class="nav-item mr-4">
                    <a class="nav-link" href="{{ url_for('views.history') }}">Watch History</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('creators.show_analytics') }}">View Analytics</a>
                </li>
            </ul>
            <button class="btn btn-outline-danger my-2 my-sm-0 nav-btn" onclick="logout()">
                Logout
            </button>
        </div>
    </nav>

    <div class="search-container px-5">
        <button type="button" class="btn btn-primary" id="upload" data-toggle="modal" data-target="#videoModal">
            <i class="fa-solid fa-cloud-arrow-up"></i>
            Upload
        </button>

        <div class="modal" id="videoModal" tabindex="-1" role="dialog" aria-labelledby="videoModalLabel"
            aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="videoModalLabel">Submit Video URL</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="videoForm" action="{{ url_for('views.upload_video') }}" method="post">
                            <div class="form-group">
                                <label for="videoUrl">Video URL:</label>
                                <input type="text" name="url" class="form-control" id="videoUrl"
                                    placeholder="Enter the URL" required />
                            </div>
                            <button type="submit" class="btn btn-danger">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <form action="{{ url_for('views.search') }}" method="POST">
            <input type="text" name="search_query" id="search-bar" placeholder="Search" value="" />
            <button type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>

    <div class="main-container">
        <div id="video-panel" style="height:800px">

        </div>

        <div id="side-panel">
            <ul id="suggested-videos">
                {% for video in search_results %}
                <li class="suggestion-link" data-video-id="{{video.videoId}}" data-search-query="{{search_query}}">
                    <a href="{{ url_for('views.video', video_id=video.videoId) }}">
                        <div class="suggestion-box">
                            <div class="suggestion-thumbnail">
                                <img src="{{ video.thumbnails.high.url }}" alt="Video Thumbnail">
                            </div>
                            <div class="suggestion-details">
                                <div class="suggestion-title">{{ video.title }}</div>
                                <div class="suggestion-description">
                                    {% set description_text = video.description[:100] + '...' if
                                    video.description|length > 100 else video.description %}
                                    {{ description_text }}
                                </div>
                            </div>
                        </div>
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <footer>
        <div id="footersiteName">
            <img src="{{ url_for('static', filename='logo.png') }}">
            <h3>VideoQuest</h3>
        </div>
        <p>©2023 by VideoQuest. All rights reserved.</p>
    </footer>

    <script>
        $(document).ready(function () {
            $('.suggestion-link').click(function (e) {
                e.preventDefault();
                var videoId = $(this).attr('data-video-id');
                var searchQuery = $(this).attr('data-search-query');

                var data = {
                    'search_query': searchQuery,
                    'video_clicked': videoId
                };

                $.ajax({
                    type: 'POST',
                    url: `{{ url_for('views.save_search_query') }}`,
                    data: JSON.stringify(data),
                    contentType: "application/json;charset=UTF-8",
                    success: function (response) {
                        console.log(response);
                    }
                });
                window.location.href = $(this).find('a').attr('href');
            });
        });
    </script>

    <script>
        $(document).ready(function () {
            $("#videoForm").submit(function (e) {
                e.preventDefault();
                var form = $(this);
                var formData = form.serialize();
                // console.log(formData)

                $.ajax({
                    type: form.attr("method"),
                    url: form.attr("action"),
                    data: formData,
                    success: function (response) {
                        if (response.success) {
                            $("#videoModal").modal("hide");
                        } else {
                            console.log('Failed to upload video.');
                        }
                    },
                    error: function () {
                        console.log(error);
                    },
                });
            });
        });
    </script>
</body>

</html>

website/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VideoQuest</title>
</head>
<body>
    <form method="post" action="{{ url_for('api.analyze_comment') }}">
        <label class="form-label" for="email">Comment</label>
        <textarea id="comment" name="comment" rows="4" cols="50" placeholder="Enter your comment here..."></textarea>
        <br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>